<section class ="center-body">
    <article id="info-web" lan ="<?php echo $lang;?>">
        <h2 class ="titulos-rigo">Rigo<span class="color-rosa"><?php echo $this->translate("Tienda",$lang);?></span></h2>
            <?php
               $_SESSION['contador'] = (isset($_SESSION['contador']))?$_SESSION['contador']:0;
                if($_SESSION['contador']>0){
                    echo "<div id =\"content-cong-cart\">"
                     . "<a id =\"btn-vaciar\" class =\"botones-carro\" href=\"#\">".$this->translate("Vaciar carrito",$lang)."</a><div style =\"clear: both;\"></div></div>"
                        ."<div class ='titulo-producto sengle-title-cart'"
                            . "><div class =\"inline \" >".$this->translate("Producto",$lang)."</div><div class =\"inline \" >".$this->translate("Especificaciones",$lang)."</div><div class =\"inline \" >".$this->translate("Precio",$lang)."</div></div>";
                    $obje = ControllerMain::makeObjects("Carrito",1);
                    $obje->mostrarCarrito($lang);
                    echo "<div class ='titulo-producto sengle-title-cart'><p style='text-align:center'>".$this->translate("Total a pagar",$lang)."</p></div>";
                    echo "<div class ='sengle-title-cart'><p style='text-align:center'>".$obje->totalCart($lang)."</p></div>";
                }else{
                    echo "<span class ='class vacio'>".$this->translate("Actualmente no hay productos en tu carrito",$lang)."</span>";
                }
            ?>
    </article>
</section>