<section class ="center-body">
    <article id ="idproducto" lan ="<?php echo $lang;?>">
        <h2 class ="titulos-rigo">Rigo<span class="color-rosa"><?php echo $this->translate("Cuenta",$lang);?></span></h2>
    </article>
    <article>
         <form id ="form-registro">
             <p>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500</p><br />
            <div class ="columna inline">
               <div class ="rows">
                   <span class ="label-form"><label>Nombre <span class ="required">*</span></label><input type ="text" name ="txtnombre" id ="txtnombre"/></span>
               </div>
               <div class ="rows">
                   <span class ="label-form"><label>Apellidos <span class ="required">*</span></label><input type ="text" name ="txtapellidos" id ="txtapellidos"/></span>
               </div>
               <div class ="rows">
                   <span class ="label-form"><label>Usuario <span class ="required">*</span></label><input type ="text" name ="txtusuario" id ="txtusuario"/></span>
               </div>
               <div class ="rows">
                   <span class ="label-form"><label>Confirma tu constraseña <span class ="required">*</span></label><input type ="text" name ="txtconstra" id ="txtconstra"/></span>
               </div>
               <div class ="rows">
                   <span class ="label-form"><label>Tipo de documento <span class ="required">*</span></label>
                       <select name ="slttipodocumento" id ="slttipodocumento">
                       </select>
                   </span>
                </div>
                <div class ="rows">
                    <span class ="label-form"><label>Nro documento <span class ="required">*</span></label><input type ="text" name ="txtndocumento" id ="txtndocumento"/></span>
                </div>
            </div>
            <div class ="columna inline">
                <div class ="rows">
                    <span class ="label-form"><label>Teléfono <span class ="required">*</span></label><input type ="text" name ="txttelefono" id ="txttelefono"/></span>
                </div>
                <div class ="rows">
                    <span class ="label-form"><label>Correo <span class ="required">*</span></label><input type ="mail" name ="txtcorreo" id ="txtcorreo"/></span>
                </div>
                <div class ="rows">
                    <span class ="label-form"><label>Pais <span class ="required">*</span></label><input type ="text" name ="txtpais" id ="txtpais" value ="Colombia"/></span>
                </div>
                <div class ="rows">
                    <span class ="label-form"><label>Departamento <span class ="required">*</span></label><input type ="text" name ="txtdepartemento" id ="txtdepartemento" /></span>
                </div>
                <div class ="rows">
                    <span class ="label-form"><label>Ciudad <span class ="required">*</span></label><input type ="text" name ="txtciudad" id ="txtciudad" /></span>
                </div>
                <div class ="rows">
                    <span class ="label-form"><label>Dirección residencia <span class ="required">*</span></label><input type ="text" name ="txtdireccion" id ="txtdireccion"/></span>
                </div>
            </div>
             <div class ="content-button"><input id ="btn-enviar-registro" type="button" class="botones-carro" value ="<?php echo $this->translate("Registrarse",$lang);?>"/></div>
        </form>
    </article>
</section>

     
                
                
                
                
               
                
                
                